apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dso202-assignment-01
  labels:
    dso202/assignment: "01"
    dso202/managed-by: declarative
type: Opaque
stringData:
  DB_USER: "taskuser"
  DB_PASSWORD: "namgyel123"
  POSTGRES_USER: "taskuser"
  POSTGRES_PASSWORD: "namgyel123"
