apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: dso202-assignment-01
  labels:
    app: database
    tier: database
    dso202/assignment: "01"
    dso202/managed-by: declarative
spec:
  clusterIP: None
  selector:
    app: database
    tier: database
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
