apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dso202-assignment-01
  labels:
    app: frontend
    tier: frontend
    dso202/assignment: "01"
    dso202/managed-by: declarative
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
        dso202/assignment: "01"
        dso202/managed-by: declarative
    spec:
      containers:
        - name: frontend
          image: sarojsanyasi/dso202-frontend:1.0
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-conf
              mountPath: /docker-entrypoint.sh
              subPath: docker-entrypoint.sh
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: nginx-conf
          configMap:
            name: frontend-nginx-conf
            defaultMode: 0755
