apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: dso202-assignment-01
  labels:
    tier: database
spec:
  serviceName: db-svc        # must match the headless Service name exactly
  replicas: 1                # see README justification — image has no replication logic
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      tier: database
  template:
    metadata:
      labels:
        tier: database
    spec:
      containers:
        - name: db
          image: sarojsanyasi/dso202-db:1.0
          imagePullPolicy: Never    # keep this ONLY if you're still on the arm64 workaround from A1
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          tier: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard   # confirm with: kubectl get storageclass
        resources:
          requests:
            storage: 1Gi
  updateStrategy:
    type: RollingUpdate
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain